---
title: "vignette-sunset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette-sunset}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(sunset)
library(tidyverse)
library(ggplot2)
library(palmerpenguins)
library(unikn)
library(colorspace)
```

### The vignette gives an overview of your palette, and the colours that are in it

```{r, fig.width = 8, fig.height=6,fig.cap="Colours in the sunset palette", fig.align='center', message=FALSE, warning=FALSE}
seecol("mountain_colours")
```

### The vignette shows how the palette can be used with ggplot2 by making a bar chart and a scatter plot on the palmerpenguins data.

```{r, fig.width = 8, fig.height=6,fig.cap="Penguin Size and Body mass", fig.align='center', message=FALSE, warning=FALSE}

penguins %>%
  group_by(species) %>% 
  ggplot(aes(x = flipper_length_mm, y = body_mass_g, color = species, shape = species)) +
  geom_point() +
  scale_color_mountain_d() +
  theme_light()

```

```{r, fig.width = 10, fig.height=6,fig.cap="Island and Flipper Length", fig.align='center', message=FALSE, warning=FALSE}

penguins %>%
  ggplot(aes(x = island, y = flipper_length_mm, fill = island)) +
  geom_col() +
  scale_fill_mountain_d() +
  theme_light()

```

```{r, fig.width = 10, fig.height=6,fig.cap="Body Mass wrt bill length and depth", fig.align='center', message=FALSE, warning=FALSE}

penguins %>%
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = body_mass_g)) +
  geom_point() +
  scale_colour_mountain_seq_c(name = "lightpink", amount = 0.8) +
  theme_light()
  

```
